In [ ]:
!pip install transformers
!pip install torch
!pip install pandas

In [ ]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from torch.utils.data import DataLoader, TensorDataset, random_split
from transformers import BertTokenizer, BertForSequenceClassification, AdamW

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

# Load your dataset
df = pd.read_csv("/content/sentences.csv", encoding='utf-8')
print(f"Dataset Records: {len(df)}")
df1 = pd.read_csv("/content/updated_transcriptions_with_senti (1).csv", encoding='utf-8')
print(f"Original Dataset Records: {len(df)}")



print(df['Sentence'].value_counts())
# Tokenize the reviews using BERT tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')



# Tokenize and encode the reviews
input_ids = []
attention_masks = []

for review in df['Sentence']:

    encoded_dict = tokenizer.encode_plus(
                        review,
                        add_special_tokens=True,
                        max_length=64,
                        truncation=True,  # Explicitly activate truncation
                        padding='max_length',  # Pad to the max_length
                        return_attention_mask=True,
                        return_tensors='pt'
                   )
    input_ids.append(encoded_dict['input_ids'])
    attention_masks.append(encoded_dict['attention_mask'])

print("="*50)
df5 = pd.DataFrame(columns=['Original Sentence', 'Tokens'])
for review in df1['Sentence']:

    encoded_dict = tokenizer.encode_plus(
                        review,
                        add_special_tokens=True,
                        max_length=64,
                        truncation=True,  # Explicitly activate truncation
                        padding='max_length',  # Pad to the max_length
                        return_attention_mask=True,
                        return_tensors='pt'
                   )
    input_ids.append(encoded_dict['input_ids'])
    attention_masks.append(encoded_dict['attention_mask'])

    input_ids = encoded_dict['input_ids'].tolist()[0]
    tokens = tokenizer.convert_ids_to_tokens(input_ids)

    # Print sentence and its tokens
    #print(f"Original Sentence:{review}" )
    #print("Tokens:", tokens)
    df5 = df5.append({'Original Sentence': review, 'Tokens': tokens}, ignore_index=True)
print(df5)
input_ids = torch.cat(input_ids, dim=0)
attention_masks = torch.cat(attention_masks, dim=0)

labels = torch.tensor(df['Label'])###Original
labels1 =torch.tensor(df1['Label'])

label_tensors = [torch.tensor(df['Label']), torch.tensor(df1['Label'])]

# Concatenating the label tensors along a specified dimension (e.g., dim=1 for concatenating horizontally)
concatenated_tensor = torch.cat(label_tensors, dim=0)

# Split the dataset into training and validation sets
print(len(input_ids))
print(len(attention_masks))
print(len(labels))

dataset = TensorDataset(input_ids, attention_masks, concatenated_tensor)#labels)
train_size = int(0.8 * len(dataset))
val_size = len(dataset) - train_size
train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

# Create DataLoader
train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=32, shuffle=False)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset Records: 1000
Original Dataset Records: 1000
السلام علیکم، میں سیون اپ پیاہوں گا اور میں ضرور کہوں گا کہ یہ میرے تجربات میں سے ایک بہترین تھا، خاص طور پر جب ہم دوستوں کے ساتھ باہر ہوتے ہیں    19
السلام علیکم، میں سیون اپ پیاتھا اور مجھے یہ بالکل بھی پسند نہیں آیا، شاید اس بار کچھ گڑبڑ تھی یا پھر ان کی کوالٹی میں کمی آئی ہے                  19
السلام علیکم، میں لیز کھائےہوں لیکن میرے خیالات اس پر واضح نہیں ہیں، یہ کچھ خاص نہیں ہے لیکن برا بھی نہیں ہے                                       19
السلام علیکم، میں لیز کھائےتھا اور میں ضرور کہوں گا کہ یہ میرے تجربات میں سے ایک بہترین تھا، خاص طور پر جب ہم دوستوں کے ساتھ باہر ہوتے ہیں         18
السلام علیکم، میں نے لیز کھائےہوں گا لیکن مجھے اس بار مایوسی ہوئی کیونکہ اس کا معیار پہلے جیسا نہیں رہا                                            17
                                                                    

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Us

                                     Original Sentence  \
0    کافی حد تک گیم ہے میں نے بہت بڑا ہے جب بھی خیر...   
1    بہت اچھے لگے میں تو بہت لائک کرتا ہوں کھاتا ہو...   
2    پیپسی جو ہے نا وہ کبھی کبھار جب وہ سچویشن پر ڈ...   
3    السلام علیکم میرا نام مرتضی ہے اور اج میں لیس ...   
4    وعلیکم میرا نام محمد حسین جہانگیر ہے اور میں ا...   
..                                                 ...   
105  جو چیز پیپسی کے بارے میں مجھے بری لگتی ہے وہ ی...   
106  اور پیپسی جو ہے وہ میں اپنا زائد ہوں اپنا نظری...   
107  میرا نام احمد ہے اوور ال پیپسی سے میں کافی مطم...   
108  میرا نام احمد ہے اور پیپسی کے بارے میں جو چیز ...   
109  اپ مجھ سے پیپسی کا ریویو لیا جا رہا ہے پیپسی ب...   

                                                Tokens  
0    [[CLS], کافی, حد, تک, گ, ##یم, ہے, میں, نے, بہ...  
1    [[CLS], بہت, ا, ##چ, ##ھے, ل, ##گے, میں, تو, ب...  
2    [[CLS], پی, ##پس, ##ی, جو, ہے, ن, ##ا, وہ, ک, ...  
3    [[CLS], السلام, علی, ##کم, می, ##را, نام, م, #...  
4    [[CLS], و, ##

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

<ipython-input-35-4caa4b1a7213>:58: FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Us

TypeError: expected Tensor as element 0 in argument 0, but got int

In [ ]:
# Load pre-trained multilingual BERT model for sentiment classification
model = BertForSequenceClassification.from_pretrained(
    'bert-base-multilingual-cased',
    num_labels=3,  # 3 classes: neutral,positive,Negative
    output_attentions=False,
    output_hidden_states=False
)


model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
# Set up optimizer and learning rate scheduler
optimizer = AdamW(model.parameters(), lr=2e-5, eps=1e-8)

# Training loop
epochs = 3
for epoch in range(epochs):
    model.train()
    for batch in train_dataloader:
        optimizer.zero_grad()
        inputs = {
            'input_ids': batch[0],
            'attention_mask': batch[1],
            'labels': batch[2]
        }
        outputs = model(**inputs)
        loss = outputs.loss
        loss.backward()
        optimizer.step()

# Validation loop
model.eval()
for batch in val_dataloader:
    inputs = {
        'input_ids': batch[0],
        'attention_mask': batch[1],
        'labels': batch[2]
    }
    outputs = model(**inputs)
    logits = outputs.logits
    # Evaluate as needed


/usr/local/lib/python3.10/dist-packages/transformers/optimization.py:411: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Evaluate on the validation set
model.eval()
all_labels = []
all_preds = []

for batch in val_dataloader:
    inputs = {
        'input_ids': batch[0],
        'attention_mask': batch[1],
        'labels': batch[2]
    }
    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits
    preds = np.argmax(logits.cpu().numpy(), axis=1)

    all_labels.extend(inputs['labels'].cpu().numpy())
    all_preds.extend(preds)

# Calculate accuracy
accuracy = accuracy_score(all_labels, all_preds)
print(f'Accuracy: {accuracy * 100:.2f}%')

# Generate confusion matrix
conf_matrix = confusion_matrix(all_labels, all_preds)
print('Confusion Matrix:')
print(conf_matrix)

# Print classification report
class_report = classification_report(all_labels, all_preds, target_names=['neutral', 'positive','negative'])
print('Classification Report:')
print(class_report)


Accuracy: 93.69%
Confusion Matrix:
[[65  4  0]
 [ 0 79  1]
 [ 0  9 64]]
Classification Report:
              precision    recall  f1-score   support

     neutral       1.00      0.94      0.97        69
    positive       0.86      0.99      0.92        80
    negative       0.98      0.88      0.93        73

    accuracy                           0.94       222
   macro avg       0.95      0.94      0.94       222
weighted avg       0.94      0.94      0.94       222



In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np
import plotly.graph_objs as go
from plotly.subplots import make_subplots

# Your existing code...

# Calculate accuracy
accuracy = accuracy_score(all_labels, all_preds)

# Generate confusion matrix
conf_matrix = confusion_matrix(all_labels, all_preds)

# Calculate precision, recall, and F1-score
class_report_dict = classification_report(all_labels, all_preds, target_names=[ 'neutral', 'positive','negative'], output_dict=True)
precision = [class_report_dict[label]['precision'] for label in [ 'neutral', 'positive','negative']]
recall = [class_report_dict[label]['recall'] for label in [ 'neutral', 'positive','negative']]
f1_score = [class_report_dict[label]['f1-score'] for label in [ 'neutral', 'positive','negative']]

# Create an interactive confusion matrix
fig = make_subplots(rows=2, cols=2, subplot_titles=['Confusion Matrix', 'Accuracy Bar Chart', 'Precision Bar Chart', 'Recall Bar Chart'])

# Confusion Matrix
trace_heatmap = go.Heatmap(z=conf_matrix,
                          x=[ 'neutral', 'positive','negative'],
                          y=[ 'neutral', 'positive','negative'],
                          colorscale='Viridis')

fig.add_trace(trace_heatmap, row=1, col=1)

# Accuracy Bar Chart
trace_bar_accuracy = go.Bar(x=['Accuracy'], y=[accuracy * 100], marker=dict(color='blue'))

fig.add_trace(trace_bar_accuracy, row=1, col=2)

# Precision Bar Chart
trace_bar_precision = go.Bar(x=[ 'neutral', 'positive','negative'], y=np.round(precision, 2) * 100, marker=dict(color='green'))

fig.add_trace(trace_bar_precision, row=2, col=1)

# Recall Bar Chart
trace_bar_recall = go.Bar(x=[ 'neutral', 'positive','negative'], y=np.round(recall, 2) * 100, marker=dict(color='orange'))

fig.add_trace(trace_bar_recall, row=2, col=2)

fig.update_layout(title_text='Confusion Matrix, Accuracy, Precision, and Recall', height=600, width=800)

fig.show()

# Print classification report
print('Classification Report:')
print(classification_report(all_labels, all_preds, target_names=[ 'neutral', 'positive','negative']))


Classification Report:
              precision    recall  f1-score   support

     neutral       0.99      0.96      0.97        73
    positive       0.91      0.99      0.95        79
    negative       0.98      0.91      0.95        70

    accuracy                           0.95       222
   macro avg       0.96      0.95      0.96       222
weighted avg       0.96      0.95      0.96       222



In [ ]:
#save a model to drive

from transformers import BertModel, BertTokenizer, BertConfig

# Assuming you have already trained a BERT model and have the necessary objects
model = BertModel.from_pretrained('bert-base-uncased')  # Replace with your actual model path

# Get the configuration from the model
config = model.config

# Save the model
model.save_pretrained('/content/drive/MyDrive/BERTModal')

# Save the tokenizer and configuration
tokenizer.save_pretrained('/content/drive/MyDrive/BERTModal')
config.save_pretrained('/content/drive/MyDrive/BERTModal')
tokenizer.save_pretrained('/content/drive/MyDrive/BERTModal')



config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

('/content/drive/MyDrive/BERTModal/tokenizer_config.json',
 '/content/drive/MyDrive/BERTModal/special_tokens_map.json',
 '/content/drive/MyDrive/BERTModal/vocab.txt',
 '/content/drive/MyDrive/BERTModal/added_tokens.json')

In [1]:
# prompt: mount gooogle drive

from google.colab import drive
drive.mount('/content/drive')


MessageError: Error: credential propagation was unsuccessful

In [ ]:
#Load existing trained Modal and use it
from transformers import BertModel, BertTokenizer

# Load the saved model
model = BertModel.from_pretrained('/content/drive/MyDrive/BERTModal')

# Load the tokenizer
tokenizer = BertTokenizer.from_pretrained('/content/drive/MyDrive/BERTModal')




